# Generated by Django 4.1.7 on 2023-02-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления записи"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Информация об авторе",
                        max_length=500,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "resume",
                    models.CharField(
                        help_text="Ссылка на резюме",
                        max_length=255,
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        help_text="Ссылка на GitHub",
                        max_length=255,
                        verbose_name="GitHub",
                    ),
                ),
                (
                    "mail",
                    models.CharField(
                        help_text="e-mail адрес", max_length=255, verbose_name="e-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обо мне",
                "verbose_name_plural": "Обо мне",
            },
        ),
    ]
