# Generated by Django 4.1.7 on 2023-02-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="description",
            new_name="about",
        ),
    ]
