# Generated by Django 4.1.7 on 2023-02-24 08:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="example value", verbose_name="Подробное описание работы"
            ),
            preserve_default=False,
        ),
    ]
